Repository pupil-dilation/pupil-dilation, pull requests merged in 2023-07, with the labels that each got.

#31 feat[#29]: 주최자 메인 페이지 하드코딩
  src/components/HostMainPage.css
  src/components/HostMainPage.js
  src/routes/MainPageRoute.js
Labels: feat

#33 Feat/#27 티켓 목록 페이지 구현(미완)
  src/components/LoginPage.js
  src/components/SignUpPage.js
  src/components/TicketList.css
  src/components/TicketList.js
  src/routes/MainPageRoute.js
Labels: feat

#36 feat[#34]: create loading page
  public/assets/Spinner.gif
  public/images/arrow-right.svg
  public/images/circle-logo.png
  public/images/ticket.png
  src/components/Loading.css
  src/components/Loading.js
Labels: feat

#38 fix[#37]: modified detail page
  src/components/Detail/DetailContent.css
  src/components/Detail/DetailContent.js
Labels: fix

#39 Feat/#32
  src/components/HostEventContent.js
  src/components/HostEventManage.css
  src/components/HostEventManage.js
  src/routes/MainPageRoute.js
Labels: feat

#41 feat[#30]: 로그인 / 회원가입 기능 추가
  .eslintrc.json
  src/Firebase.js
  src/components/LoginPage.js
  src/components/SignUpPage.js
  src/features/show/api/getShows.js
  src/features/user/api/firebase_auth.js
  src/features/user/slices/userSlice.js
Labels: feat

#44 feat[#43]: 로그인 및 회원가입 라우팅 추가
  src/components/Header.css
  src/components/Header.js
  src/components/LoginPage.css
  src/components/LoginPage.js
  src/components/SignUpPage.js
Labels: feat

#48 refactor[#47]: 폴더 구조 리팩토링
  src/components/Host/HostEventContent.js
  src/components/Host/HostEventManage.css
  src/components/Host/HostEventManage.js
  src/components/Host/HostMainPage.css
  src/components/Host/HostMainPage.js
  src/components/Login/LoginPage.css
  src/components/Login/LoginPage.js
  src/components/Login/SignUpPage.css
  src/components/Login/SignUpPage.js
  src/components/MyPage/TicketList.css
  src/components/MyPage/TicketList.js
  src/routes/MainPageRoute.js
Labels: refactor

#54 feat[#53]: create MediaQuery
  .eslintrc.json
  package-lock.json
  package.json
  src/components/MediaQuery/Desktop.js
  src/components/MediaQuery/Mobile.js
Labels: feat

#57 fix[#56]: header 로그인 시 변경
  src/components/Detail/DetailContent.js
  src/components/Detail/DetailFooter.js
  src/components/Detail/getShowById.js
  src/components/Header.css
  src/components/Header.js
  src/components/Login/LoginForm.js
  src/features/user/api/firebase_auth.js
  src/features/user/slices/userSlice.js
  src/stores/store.js
Labels: fix

#58 fix[#56]: 로그인 시 회원가입 버튼 삭제
  src/components/Header.js
Labels: fix

#59 feat[#52]: login 페이지 모바일 버전
  .firebase/hosting.YnVpbGQ.cache
  src/components/Login/LoginFormDesktop.css
  src/components/Login/LoginFormDesktop.js
  src/components/Login/LoginFormMobile.css
  src/components/Login/LoginFormMobile.js
  src/components/Login/LoginPage.js
  src/components/Login/LoginPageDesktop.css
  src/components/Login/LoginPageDesktop.js
  src/components/Login/LoginPageMobile.css
  src/components/Login/LoginPageMobile.js
  src/components/MediaQuery/Mobile.js
Labels: feat

#61 feat[#55]: 메인 페이지 보완
  src/components/Main/MainPage.js
  src/components/Main/desktop/MainPageDesktop.css
  src/components/Main/desktop/MainPageDesktop.js
  src/components/Main/desktop/SliderDesktop.css
  src/components/Main/desktop/SliderDesktop.js
  src/components/Main/image.json
Labels: feat

#69 Feat/#68
  .firebase/hosting.YnVpbGQ.cache
  public/images/upload-image.png
  src/components/Host/HostCreate.css
  src/components/Host/HostCreate.js
  src/components/Host/TicketerListPage.js
  src/components/Login/LoginForm.js
  src/components/Login/LoginFormDesktop.js
  src/components/Login/LoginFormMobile.js
Labels: feat

#71 feat[#62]: 레이아웃 수정
  src/components/Host/TicketerListPage.js
  src/components/Host/css/TicketerListPage.css
  src/components/Login/LoginForm.js
Labels: feat

#75 feat[#74]: host main read
  src/components/Host/HostMainPage.js
Labels: feat

#78 feat[#76]: show api update 추가
  src/features/show/api/showsDocumentApi.js
Labels: feat

#79 feat[#76]: show api delete 추가
  src/features/show/api/showsDocumentApi.js
Labels: feat

#82 fix[#81]: database period, schedule timestamp로 변경
  src/components/Detail/DetailContent.js
  src/components/Detail/DetailFooter.js
  src/components/Host/HostEventContent.js
  src/components/Main/desktop/SliderDesktop.js
  src/features/show/api/showsDocumentApi.js
Labels: fix

#84 feat[#72]: 예매자 목록 페이지 레이아웃 수정
  src/components/Host/TicketerListPage.js
  src/components/Host/css/TicketerListPage.css
Labels: feat

#87 feat[#85]:체크박스 상태변화 텍스트 색변경
  src/components/Host/TicketerListPage.js
  src/components/Host/css/TicketerListPage.css
Labels: feat

#88 feat[#77]: host create 창 추가
  src/components/Host/HostCreate.css
  src/components/Host/HostCreate.js
  src/components/Host/HostMainPage.js
  src/features/show/api/showsDocumentApi.js
Labels: feat

#90 feat[#73]: host delete 기능 구현
  src/components/Host/HostEventManage.js
  src/components/Host/TicketerListPage.js
Labels: feat

#91 feat[#89]: Update 데이터 받기
  src/components/Host/HostUpdate.css
  src/components/Host/HostUpdate.js
Labels: feat

#95 feat[#93]:업데이트 기능
  src/components/Host/HostEventManage.js
  src/components/Host/HostUpdate.js
  src/routes/HostPageRoute.js
Labels: feat

#99 feat[#68]: schedule subtract function add
  src/components/Host/HostCreate.css
  src/components/Host/HostCreate.js
Labels: feat

#101 feat[#96]:HostUpdate 구현완료
  .eslintrc.json
  package.json
  src/components/Host/HostCreate.js
  src/components/Host/HostUpdate.css
  src/components/Host/HostUpdate.js
  src/components/Host/HostUpdatet.js
  src/features/show/api/showsDocumentApi.js
Labels: feat

#102 feat[#100]: modify user mypage
  src/components/Main/MyPage/TicketList.css
  src/components/Main/MyPage/TicketList.js
  src/components/MyPage/TicketList.js
  src/routes/MainPageRoute.js
Labels: feat

#107 feat[#103]: 주최자 예매자 목록 페이지 복사 기능 추가
  public/images/copy-test.svg
  public/images/copy.svg
  src/components/Host/HostUpdate.js
  src/components/Host/TicketerListPage.js
Labels: feat

#111 Feat/#110
  src/components/Admin/AdminPage.css
  src/components/Admin/AdminPage.js
  src/components/Host/HostCreate.css
Labels: feat

#109 feat[#108]: 관리자 페이지 추가 구현
  src/components/Admin/AdminPage.css
  src/components/Admin/AdminPage.js
Labels: feat

#114 feat[#113]:버튼 수정
  public/images/Trash.svg
  src/components/Host/HostCreate.css
  src/components/Host/HostCreate.js
Labels: feat

#118 feat[#115]:버튼 수정(미완료)
  src/components/Host/HostCreate.css
  src/components/Host/HostCreate.js
Labels: feat

#121 feat[#119]: 에러 페이지 구현
  public/images/logo_error.png
  src/components/Error/ErrorPage.css
  src/components/Error/ErrorPage.js
  src/routes/AppRoute.js
  src/routes/HostPageRoute.js
  src/routes/LoginPageRoute.js
  src/routes/MainPageRoute.js
Labels: feat

#122 Feat/#116 결제 페이지 추가 구현
  public/images/ticketWhite.png
  src/components/Seats/Pay/PaymentPage.css
  src/components/Seats/Pay/PaymentPage.js
  src/routes/MainPageRoute.js
Labels: feat

#126 feat[#124]: 에러 페이지 추가구현 완료
  src/components/Error/ErrorPage.js
Labels: feat

#128 feat[#127]:모바일 헤더 구현
  src/components/MobileHeader.css
  src/components/MobileHeader.js
  src/containers/MainPageContainer.js
  src/routes/MainPageRoute.js
Labels: feat

#130 feat[#129]:모바일 메인 페이지 구현
  src/components/Main/MainPage.js
  src/components/Main/Mobile/MainPageMobile.css
  src/components/Main/Mobile/MainPageMobile.js
  src/components/Main/Mobile/SliderMobile.css
  src/components/Main/Mobile/SliderMobile.js
Labels: feat

#131 feat[#123]:마이페이지 구현
  package-lock.json
  package.json
  public/images/arrow-down.svg
  src/components/Main/MyPage/TicketList.css
  src/components/Main/MyPage/TicketList.js
  src/components/Seats/Pay/PaymentPage.css
  src/components/Seats/Pay/PaymentPage.js
Labels: feat

#134 feat[#132]:모바일 메인 페이지 구현
  src/components/Main/Mobile/MainPageMobile.css
  src/components/Main/Mobile/MainPageMobile.js
  src/components/Main/Mobile/SliderMobile.css
  src/components/Main/Mobile/SliderMobile.js
Labels: feat

#136 feat[#135]: 동공확장 이미지 누르면 메인 페이지로 이동
  src/components/MobileHeader.js
Labels: feat

#141 feat[#138]: userSlice modify
  src/components/Login/SignUpPage.js
  src/components/Popup/ModalFrame.js
  src/components/Popup/Popup.css
  src/components/Popup/Popup.js
  src/features/user/slices/userSlice.js
Labels: feat

#143 feat[#133]:마이페이지 추가구현
  src/components/Main/MyPage/TicketList.css
  src/components/Main/MyPage/TicketList.js
Labels: feat

#147 feat/#144
  src/components/Main/MyPage/TicketList.js
Labels: feat

#150 feat[#148]: 모바일 공연 상세 페이지 구현 완료
  src/components/Detail/desktop/DetailFooterDesktop.css
  src/components/Detail/mobile/DetailContentMobile.css
  src/components/Detail/mobile/DetailContentMobile.js
  src/components/Detail/mobile/DetailFooterMobile.js
Labels: feat

#152 feat[#138]: modal update
  src/components/Host/HostSignUp.js
  src/components/Host/TicketerListPage.js
  src/components/Login/SignUpForm.js
  src/components/Login/SignUpPage.js
Labels: feat

#153 feat[#151]: 모바일 로그인 헤더 구현 위해 폴더 재구성했습니다.
  src/components/Header/desktop/MainHeaderDesktop/MainHeaderDesktop.css
  src/components/Header/desktop/MainHeaderDesktop/MainHeaderDesktop.js
  src/components/Header/mobile/MainHeaderMobile/MainHeaderMobile.css
  src/components/Header/mobile/MainHeaderMobile/MainHeaderMobile.js
  src/containers/LoginPageContainer.js
  src/containers/MainPageContainer.js
Labels: feat

#155 feat[#151]:로그인 헤더 데스크탑용 구현 완료
  src/components/Header/desktop/LoginHeaderDesktop/LoginHeaderDesktop.css
  src/components/Header/desktop/LoginHeaderDesktop/LoginHeaderDesktop.js
  src/containers/LoginPageContainer.js
Labels: feat

#157 feat[#156]: 로그인 헤더창 모바일 버전 구현 완료
  public/img/header_logo.svg
  public/img/login_header_logo.svg
  src/components/Header/desktop/LoginHeaderDesktop/LoginHeaderDesktop.js
  src/components/Header/mobile/LoginHeaderMobile/LoginHeaderMobile.css
  src/components/Header/mobile/LoginHeaderMobile/LoginHeaderMobile.js
  src/components/Login/LoginPageMobile.css
  src/components/Login/LoginPageMobile.js
  src/containers/LoginPageContainer.js
Labels: feat

#159 feat[#138]: update modal
  src/components/Detail/desktop/DetailFooterDesktop.js
  src/components/Detail/mobile/DetailFooterMobile.js
  src/components/Host/HostCreate.js
  src/components/Host/HostUpdate.js
  src/components/Main/Mobile/MainPageMobile.js
  src/components/Main/desktop/MainPageDesktop.js
  src/components/Seats/SeatTicketingFrame.js
  src/components/Seats/SeatsPage.js
  src/containers/HostPageContainer.js
Labels: feat

#162 feat[#161]: 메인 페이지 슬라이더 세부 구현 완료
  src/components/Main/desktop/SliderDesktop.js
Labels: feat

#166 feat[#165]: search funtion
  src/components/Header/desktop/MainHeaderDesktop/MainHeaderDesktop.js
Labels: feat

#168 feat[163]: 주최자 메인 페이지 구현 중
  src/components/Host/HostMainPage.js
  src/components/Host/HostMainPage/desktop/HostMainPageDesktop.css
  src/components/Host/HostMainPage/desktop/HostMainPageDesktop.js
  src/components/Host/HostMainPage/mobile/HostMainPageMobile.css
  src/components/Host/HostMainPage/mobile/HostMainPageMobile.js
  src/components/Main/MainPage.js
Labels: feat
